language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

mysql:
  database: rorm
  username: rorm
  encoding: utf8

before_script:
  - echo "CREATE DATABASE rorm;\nCREATE USER 'rorm'@'localhost' IDENTIFIED BY 'secret';GRANT ALL PRIVILEGES ON *.* TO 'rorm'@'localhost' WITH GRANT OPTION;\n"  | mysql -u root